name: 'CI - Execução Manual (Testes com Mocha)'

on:
  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest
    continue-on-error: true  # Permite que o job continue mesmo com falha

    steps:
      - name: Clonar projeto
        uses: actions/checkout@v4

      - name: Instalar NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Executar Teste COM ERRO (02-testes.js)
        run: npx mocha ./testes/02-testes.js || echo "Teste com erro concluído - Continuando workflow"
        continue-on-error: true  # Força continuar mesmo com erro

      - name: Executar Teste SEM ERRO (01-testes.js)
        run: npx mocha ./testes/01-testes.js